(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}},r="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,g){if(a==Array.prototype||a==Object.prototype)return a;a[c]=g.value;return a},t=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var g=a[c];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");
},u=t(this),v=function(a,c){if(c)a:{var g=u;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in g))break a;g=g[f]}a=a[a.length-1];e=g[a];c=c(e);c!=e&&null!=c&&r(g,a,{configurable:!0,writable:!0,value:c})}},z=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:n(a)}};
v("Promise",function(a){function c(){this.g=null}function g(b){return b instanceof f?b:new f(function(d){d(b)})}if(a)return a;c.prototype.u=function(b){if(null==this.g){this.g=[];var d=this;this.v(function(){d.M()})}this.g.push(b)};var e=u.setTimeout;c.prototype.v=function(b){e(b,0)};c.prototype.M=function(){for(;this.g&&this.g.length;){var b=this.g;this.g=[];for(var d=0;d<b.length;++d){var h=b[d];b[d]=null;try{h()}catch(k){this.L(k)}}}this.g=null};c.prototype.L=function(b){this.v(function(){throw b;
})};var f=function(b){this.i=0;this.j=void 0;this.h=[];this.F=!1;var d=this.o();try{b(d.resolve,d.reject)}catch(h){d.reject(h)}};f.prototype.o=function(){function b(k){return function(l){h||(h=!0,k.call(d,l))}}var d=this,h=!1;return{resolve:b(this.R),reject:b(this.s)}};f.prototype.R=function(b){if(b===this)this.s(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof f)this.T(b);else{a:switch(typeof b){case "object":var d=null!=b;break a;case "function":d=!0;break a;default:d=!1}d?
this.P(b):this.D(b)}};f.prototype.P=function(b){var d=void 0;try{d=b.then}catch(h){this.s(h);return}"function"==typeof d?this.U(d,b):this.D(b)};f.prototype.s=function(b){this.I(2,b)};f.prototype.D=function(b){this.I(1,b)};f.prototype.I=function(b,d){if(0!=this.i)throw Error("Cannot settle("+b+", "+d+"): Promise already settled in state"+this.i);this.i=b;this.j=d;2===this.i&&this.S();this.N()};f.prototype.S=function(){var b=this;e(function(){if(b.O()){var d=u.console;"undefined"!==typeof d&&d.error(b.j)}},
1)};f.prototype.O=function(){if(this.F)return!1;var b=u.CustomEvent,d=u.Event,h=u.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof b?b=new b("unhandledrejection",{cancelable:!0}):"function"===typeof d?b=new d("unhandledrejection",{cancelable:!0}):(b=u.document.createEvent("CustomEvent"),b.initCustomEvent("unhandledrejection",!1,!0,b));b.promise=this;b.reason=this.j;return h(b)};f.prototype.N=function(){if(null!=this.h){for(var b=0;b<this.h.length;++b)q.u(this.h[b]);this.h=null}};
var q=new c;f.prototype.T=function(b){var d=this.o();b.l(d.resolve,d.reject)};f.prototype.U=function(b,d){var h=this.o();try{b.call(d,h.resolve,h.reject)}catch(k){h.reject(k)}};f.prototype.then=function(b,d){function h(m,p){return"function"==typeof m?function(w){try{k(m(w))}catch(x){l(x)}}:p}var k,l,y=new f(function(m,p){k=m;l=p});this.l(h(b,k),h(d,l));return y};f.prototype.catch=function(b){return this.then(void 0,b)};f.prototype.l=function(b,d){function h(){switch(k.i){case 1:b(k.j);break;case 2:d(k.j);
break;default:throw Error("Unexpected state: "+k.i);}}var k=this;null==this.h?q.u(h):this.h.push(h);this.F=!0};f.resolve=g;f.reject=function(b){return new f(function(d,h){h(b)})};f.race=function(b){return new f(function(d,h){for(var k=z(b),l=k.next();!l.done;l=k.next())g(l.value).l(d,h)})};f.all=function(b){var d=z(b),h=d.next();return h.done?g([]):new f(function(k,l){function y(w){return function(x){m[w]=x;p--;0==p&&k(m)}}var m=[],p=0;do m.push(void 0),p++,g(h.value).l(y(m.length-1),l),h=d.next();
while(!h.done)})};return f});
var A=this||self,B=function(a,c){a=a.split(".");var g=A;a[0]in g||"undefined"==typeof g.execScript||g.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===c?g=g[e]&&g[e]!==Object.prototype[e]?g[e]:g[e]={}:g[e]=c},C=function(a,c){function g(){}g.prototype=c.prototype;a.Y=c.prototype;a.prototype=new g;a.prototype.constructor=a;a.X=function(e,f,q){for(var b=Array(arguments.length-2),d=2;d<arguments.length;d++)b[d-2]=arguments[d];return c.prototype[f].apply(e,b)}},D=function(a){return a};/*

 SPDX-License-Identifier: Apache-2.0
*/
function E(a){if(Error.captureStackTrace)Error.captureStackTrace(this,E);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a))}C(E,Error);E.prototype.name="CustomError";function F(a,c){a=a.split("%s");for(var g="",e=a.length-1,f=0;f<e;f++)g+=a[f]+(f<c.length?c[f]:"%s");E.call(this,g+a[e])}C(F,E);F.prototype.name="AssertionError";var G=function(a,c){throw new F("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var H;var K=function(a,c){this.J=a===I&&c||"";this.K=J};K.prototype.toString=function(){return"Const{"+this.J+"}"};var J={},I={};var M=function(a,c){this.H=c===L?a:""};M.prototype.toString=function(){return this.H+""};var N=function(a){if(a instanceof M&&a.constructor===M)return a.H;var c=typeof a;G("expected object of type TrustedResourceUrl, got '"+a+"' of type "+("object"!=c?c:a?Array.isArray(a)?"array":c:"null"));return"type_error:TrustedResourceUrl"},L={};function O(a){var c,g,e=null==(g=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:g.call(c,"script[nonce]");(c=e?e.nonce||e.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};var P=function(a){var c;this.W=c=void 0===c?window:c;a instanceof K&&a.constructor===K&&a.K===J?a=a.J:(G("expected object of type Const, got '"+a+"'"),a="type_error:Const");if(void 0===H){c=null;var g=A.trustedTypes;if(g&&g.createPolicy)try{c=g.createPolicy("goog#html",{createHTML:D,createScript:D,createScriptURL:D})}catch(e){A.console&&A.console.error(e.message)}H=c}a=(c=H)?c.createScriptURL(a):a;this.V=new M(a,L);this.A=[];this.B=[];this.G=this.C=!1},Q=function(a){a.m.onload=function(){};a.m.onerror=
function(){};a.m.onreadystatechange=function(){}},R=function(a){var c=a.W.document,g=c.head||c.documentElement,e=c.createElement("script");a.m=e;e.async=!0;e.defer=!0;e.src=N(a.V);O(e);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(a.G=!0,Q(a),a.A.forEach(function(f){return f()}))};e.onerror=function(){a.C=!0;Q(a);a.B.forEach(function(f){return f()})};g.appendChild(e)};
P.prototype.load=function(a,c){this.G?a():this.A.push(a);this.C?c():this.B.push(c);this.m||R(this)};function S(a,c){var g=new P(a);B(c,function(e,f){e=void 0===e?function(){}:e;f=void 0===f?function(){}:f;return new Promise(function(q,b){g.load(function(){q();e()},function(){b();f()})})})}S(new K(I,"https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20220530_00_RC00/cloudshell/cloudshell.js"),"google.devops.tools.loadCloudShell");S(new K(I,"https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20220530_00_RC00/walkthrough/walkthrough.js"),"google.devops.tools.loadWalkthrough");}).call(this);
